feat(SlashCommands): add number option type
discordjs/builders pull request #23
Opened 2021-08-12 05:27 UTC by Khasms

**Please describe the changes this PR makes and why it should be merged:**
This PR adds support for the number option type as is specified [here](https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-type).

close #22 

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes 
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2021-08-12 18:17 UTC, kyranet requested changes

2021-08-12 18:17 UTC, kyranet commented on src/interactions/slashCommands/mixins/CommandOptionWithChoices.ts
> +					: 'number'
I'd suggest making an enum to convert raw types to string names, like the following:

```ts
const ApplicationCommandOptionTypeNames = {
	[ApplicationCommandOptionType.String]: 'string',
	[ApplicationCommandOptionType.Integer]: 'integer',
	[ApplicationCommandOptionType.Number]: 'number'
} as const;
```

So then we can do:

```ts
ow(name, `${ApplicationCommandOptionTypeNames[this.type]} choice name`, stringPredicate);
```

2021-08-12 18:17 UTC, kyranet commented on src/interactions/slashCommands/mixins/CommandOptionWithChoices.ts
> +					: 'number'
Same applies for the rest of the code.

2021-08-13 08:40 UTC, vladfrangu approved these changes

2021-08-13 17:01 UTC, kyranet approved these changes

2021-08-21 19:25 UTC, iCrawl approved these changes

2021-08-21 19:25 UTC, merged